// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pb/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       uint32                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentType   string                 `protobuf:"bytes,5,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	TransactionId string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	SnapToken     string                 `protobuf:"bytes,8,opt,name=snap_token,json=snapToken,proto3" json:"snap_token,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,9,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	PaidAt        string                 `protobuf:"bytes,10,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_pb_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_pb_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetSnapToken() string {
	if x != nil {
		return x.SnapToken
	}
	return ""
}

func (x *Payment) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *Payment) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Payment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       uint32                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_pb_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_pb_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentRequest) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetPaymentByOrderIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint32                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByOrderIDRequest) Reset() {
	*x = GetPaymentByOrderIDRequest{}
	mi := &file_pb_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByOrderIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByOrderIDRequest) ProtoMessage() {}

func (x *GetPaymentByOrderIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByOrderIDRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByOrderIDRequest) Descriptor() ([]byte, []int) {
	return file_pb_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentByOrderIDRequest) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetPaymentByOrderIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WebhookMidtransRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadJson   string                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookMidtransRequest) Reset() {
	*x = WebhookMidtransRequest{}
	mi := &file_pb_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookMidtransRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookMidtransRequest) ProtoMessage() {}

func (x *WebhookMidtransRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookMidtransRequest.ProtoReflect.Descriptor instead.
func (*WebhookMidtransRequest) Descriptor() ([]byte, []int) {
	return file_pb_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *WebhookMidtransRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type WebhookMidtransResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookMidtransResponse) Reset() {
	*x = WebhookMidtransResponse{}
	mi := &file_pb_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookMidtransResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookMidtransResponse) ProtoMessage() {}

func (x *WebhookMidtransResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookMidtransResponse.ProtoReflect.Descriptor instead.
func (*WebhookMidtransResponse) Descriptor() ([]byte, []int) {
	return file_pb_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *WebhookMidtransResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WebhookMidtransResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_payment_payment_proto protoreflect.FileDescriptor

const file_pb_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x18pb/payment/payment.proto\x12\x02pb\"\xde\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\rR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12!\n" +
	"\fpayment_type\x18\x05 \x01(\tR\vpaymentType\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"snap_token\x18\b \x01(\tR\tsnapToken\x12\x1f\n" +
	"\vpayment_url\x18\t \x01(\tR\n" +
	"paymentUrl\x12\x17\n" +
	"\apaid_at\x18\n" +
	" \x01(\tR\x06paidAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"b\n" +
	"\x14CreatePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\rR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"P\n" +
	"\x1aGetPaymentByOrderIDRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\rR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\";\n" +
	"\x16WebhookMidtransRequest\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\tR\vpayloadJson\"K\n" +
	"\x17WebhookMidtransResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd8\x01\n" +
	"\x0ePaymentService\x126\n" +
	"\rCreatePayment\x12\x18.pb.CreatePaymentRequest\x1a\v.pb.Payment\x12B\n" +
	"\x13GetPaymentByOrderID\x12\x1e.pb.GetPaymentByOrderIDRequest\x1a\v.pb.Payment\x12J\n" +
	"\x0fWebhookMidtrans\x12\x1a.pb.WebhookMidtransRequest\x1a\x1b.pb.WebhookMidtransResponseBGZEgithub.com/Muhammadpurwanto/ecommerce-baju/services/common/pb/paymentb\x06proto3"

var (
	file_pb_payment_payment_proto_rawDescOnce sync.Once
	file_pb_payment_payment_proto_rawDescData []byte
)

func file_pb_payment_payment_proto_rawDescGZIP() []byte {
	file_pb_payment_payment_proto_rawDescOnce.Do(func() {
		file_pb_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_payment_payment_proto_rawDesc), len(file_pb_payment_payment_proto_rawDesc)))
	})
	return file_pb_payment_payment_proto_rawDescData
}

var file_pb_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_payment_payment_proto_goTypes = []any{
	(*Payment)(nil),                    // 0: pb.Payment
	(*CreatePaymentRequest)(nil),       // 1: pb.CreatePaymentRequest
	(*GetPaymentByOrderIDRequest)(nil), // 2: pb.GetPaymentByOrderIDRequest
	(*WebhookMidtransRequest)(nil),     // 3: pb.WebhookMidtransRequest
	(*WebhookMidtransResponse)(nil),    // 4: pb.WebhookMidtransResponse
}
var file_pb_payment_payment_proto_depIdxs = []int32{
	1, // 0: pb.PaymentService.CreatePayment:input_type -> pb.CreatePaymentRequest
	2, // 1: pb.PaymentService.GetPaymentByOrderID:input_type -> pb.GetPaymentByOrderIDRequest
	3, // 2: pb.PaymentService.WebhookMidtrans:input_type -> pb.WebhookMidtransRequest
	0, // 3: pb.PaymentService.CreatePayment:output_type -> pb.Payment
	0, // 4: pb.PaymentService.GetPaymentByOrderID:output_type -> pb.Payment
	4, // 5: pb.PaymentService.WebhookMidtrans:output_type -> pb.WebhookMidtransResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_payment_payment_proto_init() }
func file_pb_payment_payment_proto_init() {
	if File_pb_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_payment_payment_proto_rawDesc), len(file_pb_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_payment_payment_proto_goTypes,
		DependencyIndexes: file_pb_payment_payment_proto_depIdxs,
		MessageInfos:      file_pb_payment_payment_proto_msgTypes,
	}.Build()
	File_pb_payment_payment_proto = out.File
	file_pb_payment_payment_proto_goTypes = nil
	file_pb_payment_payment_proto_depIdxs = nil
}
